credentials:
  usernames:
    arvel:
      email: arvel@example.com
      name: Arvel Adelar
      password: $2b$12$/LiwpsviCxtdXNddMXlyX.faYw20K1vqY5dnhSwr2xkD3OZ/G97cW
    guest:
      email: guest@example.com
      name: Guest User
      password: $2b$12$8VAo.AsTbvuaenAtz1oEqeXC3xphEn8xjQG3/xZ.PCa0tuDeQaEmq
cookie:
  expiry_days: 30
  key: b9f87171b40fd608b25976e0377155732a3fc1f6ba9f3d4fa9a288021d414317
  name: codebase_rag_cookie